# Movie Rating Prediction with Python

CodSoft Data Science Internship

In [2]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("IMDb Movies India.csv", encoding="latin1")

In [4]:
df.head()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,,NaN,NaN,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia
1,#Gadhvi (He thought he was Gandhi),(2019),109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
2,#Homecoming,(2021),90 min,"Drama, Musical",NaN,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana
3,#Yaaram,(2019),110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
4,...And Once Again,(2010),105 min,Drama,NaN,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15509 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      15509 non-null  str
 1   Year      14981 non-null  str
 2   Duration  7240 non-null   str
 3   Genre     13632 non-null  str
 4   Rating    7919 non-null   float64
 5   Votes     7920 non-null   str
 6   Director  14984 non-null  str
 7   Actor 1   13892 non-null  str
 8   Actor 2   13125 non-null  str
 9   Actor 3   12365 non-null  str
dtypes: float64(1), str(9)
memory usage: 1.2 MB

In [6]:
df.describe()

            Rating
count  7919.000000
mean      5.841621
std       1.381777
min       1.100000
25%       4.900000
50%       6.000000
75%       6.800000
max      10.000000

In [7]:
df.shape

(15509, 10)

In [8]:
df.sample(5)

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
14037,The Dancing God - Shiva,(2011),95 min,Animation,NaN,NaN,NaN,NaN,NaN,NaN
4510,Ek Se Bure Do,(2009),180 min,"Action, Comedy, Crime",4.3,62,Tariq Khan,Anita,Lankesh Bhardwaj,Snehal Dabi
10273,Nothing Unusual,(2013),NaN,Drama,NaN,NaN,Twish Mukherjee,Priyanka Mukherjee,Rahee Punyashloka,Soumyo Roy
6884,Jungle Mein Hungama,(1994),NaN,Thriller,NaN,NaN,Bhanu,Jayanth,Ban Shanker,NaN
11732,Rangbaaz,(1996),NaN,Action,5.9,45,Kanti Shah,Ishrat Ali,Arjun,Mithun Chakraborty

## Data Preprocessing

In [9]:
df.isnull().sum()

Name           0
Year         528
Duration    8269
Genre       1877
Rating      7590
Votes       7589
Director     525
Actor 1     1617
Actor 2     2384
Actor 3     3144
dtype: int64

In [10]:
df = df.dropna()

In [11]:
df.isnull().sum()

Name        0
Year        0
Duration    0
Genre       0
Rating      0
Votes       0
Director    0
Actor 1     0
Actor 2     0
Actor 3     0
dtype: int64

In [12]:
df.shape

(5659, 10)

## Data Cleaning

In [13]:
df["Year"] = df["Year"].str.extract("(\d{4})")
df["Year"] = df["Year"].astype(int)

In [14]:
df["Duration"] = df["Duration"].str.replace(" min", "", regex=False)
df["Duration"] = df["Duration"].astype(int)

In [15]:
df["Votes"] = df["Votes"].str.replace(",", "", regex=False)
df["Votes"] = df["Votes"].astype(int)

In [16]:
df.info()

<class 'pandas.DataFrame'>
Index: 5659 entries, 1 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      5659 non-null   str
 1   Year      5659 non-null   int64
 2   Duration  5659 non-null   int64
 3   Genre     5659 non-null   str
 4   Rating    5659 non-null   float64
 5   Votes     5659 non-null   int64
 6   Director  5659 non-null   str
 7   Actor 1   5659 non-null   str
 8   Actor 2   5659 non-null   str
 9   Actor 3   5659 non-null   str
dtypes: float64(1), int64(3), str(6)
memory usage: 486.3 KB

## Feature Encoding

In [17]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [18]:
categorical_columns = ["Name", "Genre", "Director", "Actor 1", "Actor 2", "Actor 3"]

for col in categorical_columns:
    df[col] = le.fit_transform(df[col])

In [19]:
df.head()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
1,0,2019,109,229,7.0,8,629,1352,2272,319
3,1,2019,110,184,4.4,35,1335,1198,719,2148
5,3,1997,147,157,4.7,827,1530,378,75,2045
6,4,2005,142,289,7.4,1086,2044,692,1112,2524
8,76,2012,82,320,5.6,326,135,1934,1175,1013

In [20]:
df.info()

<class 'pandas.DataFrame'>
Index: 5659 entries, 1 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      5659 non-null   int64
 1   Year      5659 non-null   int64
 2   Duration  5659 non-null   int64
 3   Genre     5659 non-null   int64
 4   Rating    5659 non-null   float64
 5   Votes     5659 non-null   int64
 6   Director  5659 non-null   int64
 7   Actor 1   5659 non-null   int64
 8   Actor 2   5659 non-null   int64
 9   Actor 3   5659 non-null   int64
dtypes: float64(1), int64(9)
memory usage: 486.3 KB

## Model Building

In [21]:
X = df.drop("Rating", axis=1)
y = df["Rating"]

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [23]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [24]:
model.fit(X_train, y_train)

LinearRegression()

In [25]:
y_pred = model.predict(X_test)

## Model Evaluation

In [26]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

In [27]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)
print("R² Score:", r2)

Mean Absolute Error: 1.0496136607746753
Mean Squared Error: 1.6861477339933721
Root Mean Squared Error: 1.298517513934014
R² Score: 0.08942701787247076

In [28]:
results = pd.DataFrame({
    "Actual Rating": y_test.values,
    "Predicted Rating": y_pred
})

results.head(10)

   Actual Rating  Predicted Rating
0            6.0          5.640241
1            2.4          5.857040
2            3.8          5.936924
3            3.8          5.527843
4            7.2          5.346829
5            6.3          5.526592
6            8.6          5.403463
7            3.9          6.040057
8            6.6          6.027363
9            6.6          6.352486

plt.figure(figsize=(8,6))
plt.scatter(y_test, y_pred)
plt.xlabel("Actual Rating")
plt.ylabel("Predicted Rating")
plt.title("Actual vs Predicted Ratings")
plt.show()

## Random Forest Regressor

In [31]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(random_state=42)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

In [32]:
mae = mean_absolute_error(y_test, rf_pred)
mse = mean_squared_error(y_test, rf_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, rf_pred)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)
print("R² Score:", r2)

Mean Absolute Error: 0.8542888692579506
Mean Squared Error: 1.2699613489399293
Root Mean Squared Error: 1.1269256181931127
R² Score: 0.3141807984095203

In [33]:
results = pd.DataFrame({
    "Actual Rating": y_test.values,
    "Predicted Rating": rf_pred
})

results.head(10)

   Actual Rating  Predicted Rating
0            6.0             5.031
1            2.4             6.051
2            3.8             5.335
3            3.8             4.457
4            7.2             5.212
5            6.3             5.356
6            8.6             5.322
7            3.9             5.372
8            6.6             5.646
9            6.6             6.849

In [34]:
sample = pd.DataFrame({
    "Actual Rating": y_test.iloc[:5].values,
    "Predicted Rating": rf_model.predict(X_test.iloc[:5])
})

sample

   Actual Rating  Predicted Rating
0            6.0             5.031
1            2.4             6.051
2            3.8             5.335
3            3.8             4.457
4            7.2             5.212